version: '2'
services:
  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    volumes:
      - /data/influxdb:/var/lib/influxdb
      - /data/influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    environment:
      - INFLUXDB_DB=inspectit
      - INFLUXDB_USER=inspectit
      - INFLUXDB_USER_PASSWORD=inspectit
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"

  grafana:
    image: grafana/grafana:6.1.6
    container_name: grafana
    volumes:
      - /data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb

  inspectit-cmr:
    image: inspectit/cmr:1.9.3.107
    container_name: inspectit-cmr
    volumes:
      - /data/cmr/db:/CMR/db
      - /data/cmr/storage:/CMR/storage
      - /data/cmr/config:/CMR/config
      - /data/cmr/ci:/CMR/ci
    ports:
      - "8182:8182"
      - "9070:9070"
    links:
      - influxdb

